### ISSUE TITLE
Midi output port selector shows wrong port in tooltip when port was set through code

### ISSUE THREAD

**Issue by Boscop** [jazz-soft/JZZ-gui-Player#5]
Midi output port selector shows wrong port in tooltip when port was set through code
In this case, the player was connected via code to "Web Audio" but it shows a midi port name in its tooltip:
![image](https://user-images.githubusercontent.com/535593/199982572-c71fbe6c-33fb-4127-8591-718c2887b48d.png)

My workaround is currently to set the title manually whenever the port is changed:
```js
this._player.connect(spec.port);
this._player.midiBtn.div.title = spec.name;
```

**Comment by jazz-soft** [comment]
There should be a function to set the tooltip, but it's probably not documented...
Will look at it...

**Comment by jazz-soft** [comment]
What code did you use to set the MIDI port?

**Comment by jazz-soft** [comment]
Did you use  sellect() or coonect() ?
