### ISSUE TITLE
Question - player.on events and not having to use a port

### ISSUE THREAD

**Issue by TheAlienDrew** [jazz-soft/JZZ-gui-Player#7]
Is it possible to use the player as just a means of executing functions instead of connecting to MIDI-in or MIDI-out?

e.g. I want to be able to do something like so:

```js
var player = new JZZ.gui.Player('player');
player.usePort = false;
player.on('noteOn', function(note) {
    // code to do stuff with note data
    // e.g. change color of an element to something calculated with the note
});
player.on('noteOff', function(note) {
    // code to do stuff with note data
    // e.g. revert color of an element back to some default
});
player.load(data);
player.play();
// as song plays, each note press changes another elements color, but doesn't necessarily emit any sound
```

**Comment by jazz-soft** [comment]
Hi! Thanks for asking!
You can disable the MIDI button ( https://jazz-soft.net/doc/JZZ/midiplayer.html#constructor )
and connect the player output to a widget ( https://jazz-soft.net/doc/JZZ/midithru.html )
that can execute any code when the MIDI message arrives.

**Comment by TheAlienDrew** [comment]
> Hi! Thanks for asking! You can disable the MIDI button ( https://jazz-soft.net/doc/JZZ/midiplayer.html#constructor ) and connect the player output to a widget ( https://jazz-soft.net/doc/JZZ/midithru.html ) that can execute any code when the MIDI message arrives.

This is working great, only, now how do I make sure it doesn't connect to an existing MIDI port? (seems to want to automatically connect to a midi port I'm using for something else, even though I created the logger).

**Comment by TheAlienDrew** [comment]
Wait never mind, I believe I figured it out with the following:
```js
var player = new JZZ.gui.Player({
  at: JZZ_GUI_PLAYER_ID,
  midi: false,
  ports: [JZZ_TO_MPP_VIRTUAL_MIDI_PORT_NAME]
});
```
