### ISSUE TITLE
Question - Add additional buttons?

### ISSUE THREAD

**Issue by TheAlienDrew** [jazz-soft/JZZ-gui-Player#9]
Is it possible to easily add new buttons to the gui player on demand?

Or would I have to edit the code (hoping not to...)?

**Comment by jazz-soft** [comment]
The easiest way is to add a similarly styled button next to the player.
See the index.html in https://github.com/jazz-soft/test-midi-files for an example.

**Comment by TheAlienDrew** [comment]
Ah yeah I figured. Thanks I guess.
